### ISSUE TITLE
mqtt update failed and device not present

### ISSUE THREAD

**Issue by willi4m26** [wubbl0rz/FiatChamp#18]
hi, thanks for the project. I have a problem. I entered all the data and everything seems to be correct but I can't find my car, a jeep, in the mqtt devices. I installed it 2 days ago and yesterday I took the car and the uconnect app is updated to yesterday. Can you tell me where am I wrong? I have Official Home Assistant MQTT Addon. A thousand thanks

![image](https://user-images.githubusercontent.com/96135822/202862698-26378547-d6c2-4530-9ecc-e7f76aa6b5a7.png)

![image](https://user-images.githubusercontent.com/96135822/202862807-7f6181f1-4e2b-4d83-8a4d-86b623f2f576.png)

![image](https://user-images.githubusercontent.com/96135822/202862926-776074c1-0f46-43bc-b414-c04ab0352b73.png)

**Comment by wubbl0rz** [comment]
i think its related to https://github.com/wubbl0rz/FiatChamp/issues/17 

other users reported jeep does not work 😁 have you updatet to 3.0.1 and set the region ? i guess you are EU based ? i think i know where the bug is ... must be in one of the new urls and apikeys for jeep.

PS: if all that does not work just switch the brand to fiat. this is the default and should work if your car has worked yesterday.

**Comment by willi4m26** [comment]
yes exactly i'm in eu, you got it from the poor translation :) ok now i just changed to fiat, i thought i couldn't do it having jeep brand. I still can't find my car but tonight I use it a bit, the uconnect app updates and then tomorrow I'll see.

**Comment by wubbl0rz** [comment]
sorry i didnt read your message correct. i trought it worked yesterday :smile: if it does not create any entries in mqtt something is wrong. i will push an update i a few minutes pls try again with 3.0.2. the problem is fiat uses different urls and different keys in all thr regions. so i fixed the america jeep and maybe broke eu jeep :sweat: 

can you try with the official site if it works for your car ? https://myuconnect.jeep.com/

**Comment by wubbl0rz** [comment]
pls try version 3.0.2 its updated now. and if https://myuconnect.jeep.com/ works... i am optimistic that we can make it work with the addon.

**Comment by willi4m26** [comment]
ok thanks :) , it still won't give me the update.. yes, the jeep site recognizes my car and I enter the site regularly.

**Comment by wubbl0rz** [comment]
now it works without error but has no data ? 

can you enable debug in the addon options and see if it finds cars on your account ? there should be alot of json output and information about the car and location etc. pls be careful dont post uncensored debug output to github it contains sensitive information 👈 

can you look if there is output like this ?

```
[17:04:11 DBG] {                                                                                                                                   
  "Userid": "XXXXXXXXXXXXX",                                                                                                    
  "Version": 0,                                                                                                                                    
  "Vehicles": []                                                                                                                                   
}   
```

then login etc. works but no car is found.

**Comment by willi4m26** [comment]
gives me vehicle []
can't find anything for me?

![immagine](https://user-images.githubusercontent.com/96135822/202865903-057728be-7220-4727-b67e-d77c8423a4d6.png)

**Comment by willi4m26** [comment]
Sorry, I checked on the Jeep site and my vehicle is missing. There are no vehicles. Maybe that's the problem. I try to insert it so maybe it works.

**Comment by wubbl0rz** [comment]
that looks like the problem. car must be controllable via https://myuconnect.jeep.com/  😄 if you get it to work i can have a look again.

**Comment by wubbl0rz** [comment]
i will close the issue. if you get your car working with official site and it still does not work feel free to open a new issue :smile:
